services:
    develit_ab.payex.payment_manager:
        alias: DevelitAB\PayexBundle\Services\PaymentManager
        public: true
    DevelitAB\PayexBundle\Repository\PayexPaymentRepository:
        autowire: true
        public: false
        tags: ['doctrine.repository_service']
    DevelitAB\PayexBundle\Services\PaymentManager:
        public: false
        arguments:
            - '%develit_ab.payex.config%'
            - '@doctrine.orm.entity_manager'
